### PR TITLE
updated README.md

### PR DESCRIPTION
**Pull request by bharat226g**
Some badly needed README changes.

### CODE REVIEW

**Comment by chris-se** [comment]
Oh, sorry, I completely overlooked this pull request. I'll gladly merge it (thanks!), but I do not want to reference external images. Would you be OK with me adding those images to the repository itself, also under the LGPLv2.1+ license? (You don't have to change your pull request, I can merge it and move the images myself, I just need your permission first.)

**Comment by bharat226g** [comment]
I'm OK with adding the images to the repository under any license.  Please feel free to do so. I only wanted the README to be clear. Thanks :)

**Comment by chris-se** [comment]
Thanks a lot, merging your pull request first, then adding the images afterwards.

**Comment by chris-se** [comment]
So I've referenced the images from the repository now (thanks again) and also did some further updates to README.md, especially w.r.t. Debian-based distro integration (both how to properly enable it via `~/.xsessionrc` and also mentioned that there now are packages of this available in Debian unstable). Hope that is OK with you.

**Comment by bharat226g** [comment]
Thanks for those extra updates, it is more clear now.

**Pull request merged**
