### PR TITLE
Various fixes (v2)

### LINKED ISSUE #2: deadbeef crashes in the gtk2 plugin
I just compiled and installed gtk3-nocsd as recommended in the README (except I put the exports in ~/.zprofile since I use zsh), on Arch Linux 64 bit, and rebooted. Most programs seem to work fine (and CoreBird now has window borders!), but deadbeef crashes:

starting deadbeef 0.6.2
(...)
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
found selected GUI plugin: GTK2
loading plugin /usr/lib/deadbeef/ddb_gui_GTK2.so
(...)
convgui: gtkui plugin not found
plugin Converter GTK3 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK3 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK3 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 2.24.24
Segmentation Fault
backtrace() returned 2 addresses
deadbeef() [0x403aa1]
/usr/lib/libc.so.6(+0x33df0) [0x7f7cf237bdf0]

gdb backtrace:
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff7bdb14a in g_type_register_static_simple ()
   from /mnt/disk/builds/gtk3-nocsd/gtk3-nocsd/gtk3-nocsd.so
#2  0x00007ffff655271c in gdk_display_manager_get_type ()
   from /usr/lib/libgdk-x11-2.0.so.0
#3  0x00007ffff6552759 in gdk_display_manager_get ()
   from /usr/lib/libgdk-x11-2.0.so.0
#4  0x00007ffff692e30b in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#5  0x00007ffff6914cc8 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#6  0x00007ffff47eebb7 in g_option_context_parse ()
   from /usr/lib/libglib-2.0.so.0
#7  0x00007ffff6915238 in gtk_parse_args () from /usr/lib/libgtk-x11-2.0.so.0
#8  0x00007ffff6915299 in gtk_init_check () from /usr/lib/libgtk-x11-2.0.so.0
#9  0x00007ffff69152b9 in gtk_init () from /usr/lib/libgtk-x11-2.0.so.0
#10 0x00007ffff6e90c04 in gtkui_thread ()
   from /usr/lib/deadbeef/ddb_gui_GTK2.so
#11 0x00007ffff6e914d9 in ?? () from /usr/lib/deadbeef/ddb_gui_GTK2.so
#12 0x00000000004036b8 in ?? ()
#13 0x00007ffff7126000 in __libc_start_main () from /usr/lib/libc.so.6
#14 0x000000000040398a in ?? ()

### LINKED ISSUE #4: Pulseaudio doesn't start with gtk3-nocsd
Here's the error I get when I try to launch pulseaudio with gtk3-nocsd added to my .bashrc file.

[albi@albi-desktop ~]$ pulseaudio --start
pulseaudio: symbol lookup error: /home/albi/.config/gtk3-nocsd.so: undefined symbol: gtk_window_get_type

### PR DESCRIPTION
**Pull request by chris-se**
This is the second version of my pull request containing various fixes:

 - fix crashes when plugins/modules linked against gtk2/gtk3 are used (e.g. pygtk) (fixes #2)
 - remove duplicate close etc. buttons from the header bar when disabling CSD (WM provides those)
 - fix potential multithreading problem
 - switch to Makefile style build system
 - add .gitignore
 - always lookup symbols dynamically at run time (fixes #4)

There is an additional issue with popovers I noticed earlier, but that appears to be a generic problem with Gtk, see https://bugzilla.gnome.org/show_bug.cgi?id=729644 - I don't think that can be solved at all. The other issue I thought I had was about minimizing dialogs, but it actually is not gtk3-specific, but something my WM does, so it's not actually a problem.

/cc @xtaran

### CODE REVIEW

**Comment by PCMan** [comment]
Tested and it works. However, for some reason my window manager "openbox" does not show the title bar of gtk3 apps even when GTK_CSD=0. So, I lost the close/minimize buttons since you removed them. I'm still investigating the cause of the problem.
BTW, I'm a little bit busy recently and might not be able to handle pull requests in time.
Just did some quick code review and thought that you did a great job.
So, I added you to the collaborators of this repository. You should have git write access now.
Please feel free to fix bugs as you find them. :-)
Thank you for the contributions.

**Comment by PCMan** [comment]
I have gtk+ 3.16.3 and openbox 3.6 here.
Exporting GTK_CSD=0 does not seem to work for file-roller, nautilus, and devhelp.
They still fail to show the window border provided by openbox.
So with your patch, all of the close/min/max buttons are gone. :-(

**Comment by chris-se** [comment]
Hmm, works for me with openbox 3.5.2 and gtk+ 3.14.5 (Debian Jessie). Could be that something in gtk+ 3.16 changed so that what you're doing doesn't work anymore. I'll look into that.

Btw. GTK_CSD=0 is now irrelevant, that was a flag in old gtk versions to disable it (because it was still experimental) but is now not used at all anymore - just preload the library.

Thanks for adding me to the project. Once I figured out the problem with gtk+ 3.16, I'll merge the changes. Could you (after you test that) then do an initial release? (That would make it easier for me to then package for Debian.)

**Comment by chris-se** [comment]
Well, I can reproduce that with gtk+ 3.16 (and not only with openbox), I'm looking into it.

And sorry about my remark w.r.t. GTK_CSD=0, I don't know where I got that, but apparently it IS still queried (I could have sworn I had grepped for it earlier.) But at least on Debian's gtk+ 3.14 it doesn't have any effect - the nocsd lib works regardless of this setting.

**Comment by PCMan** [comment]
Thank you for looking into this. I probably don't have the time for it this week.
If you find a solution, feel free to push your changes. :-)
Then later let's make a release!

**Comment by chris-se** [comment]
I've looked at the source code of gtk 3.16 and there `gtk_window_set_titlebar` unconditionally calls `gtk_window_enable_csd`. I then tried to hack something crazy together that hooks into a couple of GTK functions to figure out the position of the `client_decorated` flag in memory and reset it - unfortunately, all functions that `gtk_window_set_titlebar` calls in that area are also Gtk functions - which means we have the problem that it's not possible to override them via `LD_PRELOAD` for the purposes of that call (only when a library calls another library does that work).

This leaves me with the conclusion that unless you want to go so far as dynamically modify GTK code in memory or start doing really weird (platform-dependent) tricks with the GOT or similar, one cannot create a preloaded library for Gtk 3.16+ that disables CSDs anymore. That's unfortunate, but I see no real alternative. (I tried to override `gdk_window_set_decorations` instead and that kind-of worked to some extent, but the decorations were unusable with openbox, probably because also other settings play a role here, so that's not an option either.) Well of course one could simply replace the entire code of `gtk_window_set_titlebar`, but I'm not at all comfortable with that...

So I think unfortunately this is the end of the line, I don't think this can be salvaged. The only way I see to disable CSDs now is to really patch gtk... :-(

Thanks for your support and sorry for wasting your time. :-(

Closing this pull request since it's only useful for 3.14 and while it doesn't crash or 3.16, it's harmful because as you said the window buttons don't appear there anymore.

**Comment by PCMan** [comment]
There's still a chance.
Please see https://git.gnome.org/browse/gtk+/tree/gtk/gtkwindow.c#n4093
static void
gtk_window_enable_csd (GtkWindow *window)
{
  GtkWindowPrivate *priv = window->priv;
  GtkWidget *widget = GTK_WIDGET (window);
  GdkVisual *visual;

  /* If the environment does not support CSD, then there's no point in enabling them */
  if (!gtk_window_can_use_csd (window))
    return;

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
In theory, if gtk_window_can_use_csd() returns FALSE, enable_csd has no effect.
Setting GTK_CSD=0 should make gtk_window_can_use_csd() return FALSE according to the source code, but I don't know why it does not work.

**Comment by PCMan** [comment]
Oh, this check does not exist in gtk+ 3.16, but it's added to gtk+ 3 in git.
So anyways, this hack will work with gtk+ 3.17.
Just adding "gtk+ 3.16" is not supported to README is enough.

**Comment by chris-se** [comment]
Ah ok, thanks, I'll have a look at that. Then we could probably add some checks to see if the gtk version is >= 3.15  and < 3.17 and not do anything there at all.

**Comment by chris-se** [comment]
So I've now added some additional version checks that make sure that the buttons don't disappear if CSDs can't be deactivated. Should the patch in gtk git gets backported to 3.16, we'll have to refine those checks. (But the current state is conservative, i.e. it rather leaves CSDs than breaks things.)

I've tested that against Gtk 3.14 (Debian Jessie's), 3.16 (most recent vanilla upstream) and (current) git and it now works as expected (where with 3.16 it doesn't see any effect) - and tested it in both KWin and Openbox.

If you don't have any objections, I'll merge this into master later.

**Comment by PCMan** [comment]
On Fri, Jun 12, 2015 at 12:47 AM, Christian Seiler <notifications@github.com
> wrote:

> So I've now added some additional version checks that make sure that the
> buttons don't disappear if CSDs can't be deactivated. Should the patch in
> gtk git gets backported to 3.16, we'll have to refine those checks. (But
> the current state is conservative, i.e. it rather leaves CSDs than breaks
> things.)
>
> I've tested that against Gtk 3.14 (Debian Jessie's), 3.16 (most recent
> vanilla upstream) and (current) git and it now works as expected (where
> with 3.16 it doesn't see any effect) - and tested it in both KWin and
> Openbox.
>
> If you don't have any objections, I'll merge this into master later.
>
No, I don't. I appreciated your work much.
Please go ahead.
Cheers!

**Comment by chris-se** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was 73dd83ebf0e12dad6e25d5eea7b1bdc681974893, new (rebased) HEAD is 8535a1468936c1b5d441b5681adc6f23ee0cae1a

**Pull request closed without merging**
